# V1.5 full-flow dry-run command list.
# Review each command and gate before executing. Controlled writes are placeholders only.
$env:PYTHONPATH = "src"

# load_plan_and_traceability: Prepare V1.5 formal plan and certificate snapshots
python -m gas_calibrator.tools.prepare_v1_5_formal_run_package --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_run_package --operator V1.5-contract-refresh --analyzer-id multi_device --run-id v1_5_contract_reference --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\configs\default_config.json

# formal_initialization_contract_plan: Generate formal initialization contract and DB bundle
python -m gas_calibrator.tools.run_v1_5_formal_initialization_runner --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\configs\default_config.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization --run-id v1_5_contract_reference_initialization --operator V1.5-contract-refresh

# initialization_readiness_snapshot: Export initialization readiness sidecar before live gates
python -m gas_calibrator.tools.export_v1_5_initialization_readiness --run-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\configs\default_config.json --getco-snapshot-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot --aux-neutralization-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\auxiliary_senco56789_neutralization --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization

# pre_gas_readiness_snapshot: Summarize pre-gas readiness gates before live identity
python -m gas_calibrator.tools.export_v1_5_pre_gas_readiness --run-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract --initialization-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\configs\default_config.json --initialization-readiness-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization\v1_5_initialization_readiness.json --database-sidecar-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization\v1_5_initialization_database_sidecar.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pre_gas_readiness

# device_identity_and_getco_snapshot: Read device IDs and GETCO1-9 before calibration
python -m gas_calibrator.tools.probe_v1_5_getco_component_snapshot --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\configs\default_config.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot --groups 1,2,3,4,5,6,7,8,9 --response-timeout-s 2.5 --command-gap-s 1.2 --attempts-per-group 3 --pre-drain-s 0.5 --identity-timeout-s 5.0 --include-legacy --allow-runtime-identity-rebind

# identity_getco_readiness_snapshot: Validate identity-bound GETCO epoch-0 evidence
python -m gas_calibrator.tools.export_v1_5_getco_identity_readiness --getco-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\identity_getco_readiness --fail-on-not-ready

# auxiliary_senco56789_neutralization_gate: Neutralize auxiliary SENCO5-9 after epoch-0 GETCO backup
# blocked/manual: blocked_pending_explicit_authorization

# pressure_quick_check: Verify analyzer pressure input against COM22 at atmosphere
python -m gas_calibrator.tools.validate_pressure_only --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot\runtime_identity_bound_config.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel --run-id v1_5_contract_reference_pressure_quick --pressure-points ambient --count 10 --interval-s 1 --continuous-atmosphere-hold --require-continuous-atmosphere-hold --no-prompt

# pressure_senco9_no_write_acquisition: If pressure fails, collect SENCO9 no-write multi-pressure evidence
python -m gas_calibrator.tools.validate_pressure_only --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot\runtime_identity_bound_config.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\senco9_no_write_acquisition --run-id v1_5_contract_reference_pressure_senco9_no_write --pressure-points 1100,1000,900,800,700,600,500 --count 12 --interval-s 1 --continuous-atmosphere-hold --require-continuous-atmosphere-hold --control-pressure-points --pressure-control-tolerance-hpa 1.0 --pressure-control-stable-s 8.0 --pressure-control-timeout-s 240.0 --pressure-control-poll-s 0.5 --pressure-control-slew-mode max --pressure-control-atmosphere-release-wait-s 1.5 --pressure-control-post-stable-wait-s 8.0 --pressure-control-analyzer-stream-flush-s 2.0 --pre-sample-freshness-timeout-s 4.0 --pre-sample-signal-max-age-s 1.0 --analyzer-active-upload-hz 1 --no-prompt

# pressure_senco9_no_write_review: If pressure acquisition ran, evaluate SENCO9 no-write candidates
python -m gas_calibrator.tools.export_v1_5_pressure_senco9_evaluation --run-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\senco9_no_write_acquisition\v1_5_contract_reference_pressure_senco9_no_write --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\senco9_no_write_evaluation --analyzer-prefix all --min-distinct-pressure-points 3 --min-pressure-span-hpa 300.0 --discard-initial-samples-per-pressure-point 1

# pressure_channel_completion_audit: Export pressure-channel completion package after SENCO9 write and post-write verification
python -m gas_calibrator.tools.export_v1_5_pressure_channel_completion --senco9-write-summary D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\senco9_controlled_write\senco9_write_summary.csv --post-write-fit-summary D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\post_write_pressure_verify\pressure_fit_summary.csv --pressure-reference-json "<pressure_reference_json>" --old-getco-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot\old_component_coefficients_snapshot.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\pressure_channel_completion

# temperature_channel_fast_review: Review SENCO7/SENCO8 temperature input evidence
python -m gas_calibrator.tools.export_v1_5_temperature_channel_review --h2o-points-parent D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\h2o_open_flow --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\temperature_channel_review

# co2_open_flow_sampling: Run V1.5 CO2 open-flow multi-temperature queue
python -m gas_calibrator.tools.run_v1_5_formal_co2_open_flow_queue --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot\runtime_identity_bound_config.json --queue-csv "<co2_runner_queue.csv>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\co2_open_flow --run-id v1_5_contract_reference_co2 --analyzer-acquisition active_stream_1hz --temperature-order desc --no-prompt

# h2o_open_flow_sampling: Run V1.5 H2O open-flow multi-temperature queue
python -m gas_calibrator.tools.run_v1_5_formal_h2o_open_flow_queue --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot\runtime_identity_bound_config.json --queue-csv "<h2o_runner_queue.csv>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\h2o_open_flow --run-id v1_5_contract_reference_h2o --analyzer-acquisition active_stream_1hz --temperature-order asc --h2o-pressure-presample-policy skip --no-prompt

# factory_signal_health_review: Review factory-mode optical reference and signal health
python -m gas_calibrator.tools.export_v1_5_factory_signal_health_review --point-means-csv "<offline_fit_point_means.csv>" --residuals-csv "<candidate_fit_residuals.csv>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\factory_signal_health_review

# fit_input_quality_review: Audit CO2/H2O fit inputs before candidate coefficients
python -m gas_calibrator.tools.export_v1_5_fit_input_quality --co2-policy-csv "<co2_candidate_policy.csv>" --co2-residuals-csv "<co2_candidate_residuals.csv>" --h2o-policy-csv "<h2o_candidate_policy.csv>" --h2o-residuals-csv "<h2o_candidate_residuals.csv>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\fit_input_quality

# post_run_coefficient_executor: Build post-run coefficient review, write, reverify, and archive gap plan
python -m gas_calibrator.tools.export_v1_5_post_run_coefficient_executor --run-dir "<completed_v1_5_run_dir>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_run_coefficient_executor --plan-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_run_package\formal_plan_snapshot.json --pressure-reference-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_run_package\com22_pressure_reference.json --run-evidence-status-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\v1_5_run_evidence_status.json --pressure-review-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\pressure_senco9_review.json --pressure-completion-summary-csv D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\pressure_channel_completion\pressure_channel_completion_summary.csv --pressure-device-readiness-csv D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pressure_channel\pressure_channel_completion\pressure_channel_device_readiness.csv --temperature-review-csv D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\temperature_channel_review\temperature_current_point_review.csv --main-precheck-meta-json "<main_senco_write_precheck_meta.json>" --post-write-reverification-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_write_reverification\post_write_reverification_review.json --archive-closure-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\v1_5_formal_archive_closure_index.json

# full_flow_closure_readiness: Review full-flow closure readiness before controlled writes
python -m gas_calibrator.tools.export_v1_5_full_flow_closure_readiness --run-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\full_flow_closure_readiness --full-flow-plan-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\v1_5_full_flow_plan.json --run-evidence-status-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\v1_5_run_evidence_status.json --post-run-executor-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_run_coefficient_executor\executor_manifest.json --controlled-write-package-csv D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_run_coefficient_executor\controlled_write_package.csv --post-write-reverification-plan-csv D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_run_coefficient_executor\post_write_reverification_plan.csv --archive-gap-list-csv D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_run_coefficient_executor\archive_gap_list.csv --archive-closure-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\v1_5_formal_archive_closure_index.json

# co2_candidate_write_review: Review CO2 SENCO1/SENCO3 and optional SENCO5 candidates
python -m gas_calibrator.tools.export_v1_5_co2_senco_pair_model_scope --original-points-xlsx "<v1_5_original_points.xlsx>" --candidate-dir "<co2_candidate_dir>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\co2_candidate_write_review

# controlled_component_write_placeholder: Controlled component writes create new coefficient epochs
# blocked/manual: blocked_pending_explicit_authorization

# post_write_reverification_placeholder: Verify analyzer outputs after controlled coefficient writes
python -m gas_calibrator.tools.export_v1_5_post_write_reverification --verification-csv "<post_write_verification_points.csv>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\post_write_reverification --write-event-json "<coefficient_write_events.json>" --coefficient-snapshot-json "<coefficient_epoch_n_snapshot.json>"

# formal_evidence_sidecar: Build formal evidence bundle from completed run artifacts
python -m gas_calibrator.tools.run_v1_5_formal_evidence_sidecar --run-dir "<completed_v1_5_run_dir>" --plan-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_run_package\formal_plan_snapshot.json --pressure-reference-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_run_package\com22_pressure_reference.json --config D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\coefficient_epoch_0_getco_snapshot\runtime_identity_bound_config.json

# formal_database_dry_run_snapshot: Preview V1.5 PostgreSQL 18 schema and insert contract
python -m gas_calibrator.tools.export_v1_5_formal_database_dry_run --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_dry_run --fail-on-blocker

# formal_database_import_preflight_snapshot: Review PostgreSQL 18 import preflight without connecting
python -m gas_calibrator.tools.export_v1_5_formal_database_import_preflight --formal-database-dry-run-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_dry_run\v1_5_formal_database_dry_run.json --dsn-env V1_5_POSTGRES_DSN --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_preflight --fail-on-blocker

# formal_database_import_authorization_snapshot: Review PostgreSQL 18 manual import authorization without connecting
python -m gas_calibrator.tools.export_v1_5_formal_database_import_authorization --formal-database-import-preflight-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_preflight\v1_5_formal_database_import_preflight.json --archive-closure-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\v1_5_formal_archive_closure_index.json --operator D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\V1.5-contract-refresh --authorization-id "<database_import_authorization_id>" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_authorization --fail-on-blocker

# formal_database_import_command_contract_snapshot: Review PostgreSQL 18 import command contract without connecting
python -m gas_calibrator.tools.export_v1_5_formal_database_import_command_contract --formal-database-import-authorization-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_authorization\v1_5_formal_database_import_authorization.json --formal-database-import-preflight-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_preflight\v1_5_formal_database_import_preflight.json --archive-closure-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\v1_5_formal_archive_closure_index.json --evidence-bundle-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\evidence_bundle.json --dsn-env V1_5_POSTGRES_DSN --requested-command-module gas_calibrator.tools.import_v1_5_evidence_package --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_command_contract --fail-on-blocker

# formal_database_import_blocked_executor_snapshot: Run blocked PostgreSQL 18 import executor stub without connecting
python -m gas_calibrator.tools.import_v1_5_evidence_package --formal-database-import-command-contract-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_command_contract\v1_5_formal_database_import_command_contract.json --formal-database-import-authorization-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_authorization\v1_5_formal_database_import_authorization.json --formal-database-import-preflight-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_preflight\v1_5_formal_database_import_preflight.json --archive-closure-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\v1_5_formal_archive_closure_index.json --evidence-bundle-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\evidence_bundle.json --dsn-env V1_5_POSTGRES_DSN --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_blocked_executor --fail-on-blocked

# database_import: Import evidence bundle into V1.5 PostgreSQL registry
python -m gas_calibrator.tools.import_v1_5_evidence_package --run-dir "<completed_v1_5_run_dir>"

# zh_calibration_reports: Generate Chinese V1.5 calibration reports
python -m gas_calibrator.tools.export_v1_5_calibration_reports --evidence-bundle-json "<completed_v1_5_run_dir>\formal_evidence_sidecar\evidence_bundle.json" --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\reports

# final_evidence_status_refresh: Refresh final V1.5 evidence status after reports and per-device certificates
python -m gas_calibrator.tools.export_v1_5_run_evidence_status --run-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract --full-flow-plan-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\v1_5_full_flow_plan.json --contract-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\v1_5_formal_flow_contract.json --evidence-bundle-json "<completed_v1_5_run_dir>\formal_evidence_sidecar\evidence_bundle.json"

# algorithm_profile_runner_dry_run_snapshot: Generate new-algorithm profile runner dry-run bundle
python -m gas_calibrator.tools.export_v1_5_algorithm_profile_runner_dry_run --profile-path D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\configs\v1_5_algorithm_route_profiles.json --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\algorithm_profile_runner_dry_run --fail-on-blocker

# formal_run_status_snapshot: Export top-level formal run status dashboard
python -m gas_calibrator.tools.export_v1_5_formal_run_status --run-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract --output-dir D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_run_status --initialization-readiness-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_initialization\v1_5_initialization_readiness.json --pre-gas-readiness-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\pre_gas_readiness\v1_5_pre_gas_readiness.json --getco-readiness-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\identity_getco_readiness\v1_5_getco_identity_readiness.json --run-evidence-status-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\v1_5_run_evidence_status.json --full-flow-closure-readiness-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\full_flow_closure_readiness\v1_5_full_flow_closure_readiness.json --archive-closure-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_archive_closure_from_full_chain\v1_5_formal_archive_closure_index.json --algorithm-profile-runner-dry-run-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\algorithm_profile_runner_dry_run\v1_5_algorithm_profile_runner_dry_run.json --formal-database-dry-run-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_dry_run\v1_5_formal_database_dry_run.json --formal-database-import-preflight-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_preflight\v1_5_formal_database_import_preflight.json --formal-database-import-authorization-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_authorization\v1_5_formal_database_import_authorization.json --formal-database-import-command-contract-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_command_contract\v1_5_formal_database_import_command_contract.json --formal-database-import-blocked-executor-json D:\gas_calibrator\_worktrees\v1_5_fixed_wait_window_gate_1aee26d_clean\docs\v1_5_flow_contract\formal_database_import_blocked_executor\v1_5_formal_database_import_blocked_executor.json
