"""Export a reviewer-facing inventory of V1.5 entrypoints."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Iterable, Optional

from ..validation.v1_5_entrypoint_inventory import discover_v1_5_entrypoints, summarize_entrypoints


def _parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export V1.5 entrypoint inventory.")
    parser.add_argument("--repo-root", default=".", help="Repository root to scan.")
    parser.add_argument("--output-dir", required=True, help="Directory for inventory artifacts.")
    return parser.parse_args(list(argv) if argv is not None else None)


def _write_csv(path: Path, rows: list[dict]) -> None:
    header: list[str] = []
    for row in rows:
        for key in row:
            if key not in header:
                header.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=header)
        writer.writeheader()
        writer.writerows(rows)


def _write_markdown(path: Path, rows: list[dict], summary: dict[str, int]) -> None:
    lines = [
        "# V1.5 formal entrypoint inventory",
        "",
        "This file is generated by `python -m gas_calibrator.tools.export_v1_5_entrypoint_inventory`.",
        "",
        "## Safety Boundary",
        "",
        "- This inventory is offline evidence only.",
        "- It does not open COM ports, control gas/water routes, control pressure, or write SENCO.",
        "- `diagnostic_only` entries must not be used as formal acceptance inputs by default.",
        "- `controlled_write` entries require explicit coefficient-write authorization and readback evidence.",
        "- Gas analyzer COM ports are transport paths; device identity must remain MODE2/device-ID based.",
        "",
        "## Category Summary",
        "",
        "| Category | Count |",
        "|---|---:|",
    ]
    for category, count in summary.items():
        lines.append(f"| `{category}` | {count} |")

    lines.extend(
        [
            "",
            "## Formal-Use Categories",
            "",
            "- `formal_runner`: candidate production runners for V1.5 physical operations.",
            "- `formal_review_evidence`: offline review, package, report, fit, and evidence exporters.",
            "- `controlled_write`: authorized write tools only; never run as background review steps.",
            "- `diagnostic_only`: engineering probes and investigations; preserve as evidence but keep out of formal acceptance by default.",
            "- `advanced_qc`, `evidence_database`, `full_flow_orchestration`, `parameter_governance`, `ui_review`: support layers.",
            "",
            "## Entrypoints",
            "",
            "| Category | Stage | Status | Risk | Path | Notes |",
            "|---|---|---|---|---|---|",
        ]
    )
    for row in sorted(rows, key=lambda item: (item["category"], item["stage"], item["path"])):
        notes = "; ".join(row.get("notes") or [])
        lines.append(
            f"| `{row['category']}` | `{row['stage']}` | `{row['formal_status']}` | "
            f"`{row['risk_level']}` | `{row['path']}` | {notes} |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = _parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    entries = discover_v1_5_entrypoints(repo_root)
    rows = [entry.to_json() for entry in entries]
    summary = summarize_entrypoints(entries)

    payload = {
        "schema": "v1_5_entrypoint_inventory_v1",
        "repo_root": str(repo_root),
        "entrypoint_count": len(rows),
        "category_summary": summary,
        "entries": rows,
    }
    json_path = output_dir / "v1_5_entrypoint_inventory.json"
    csv_path = output_dir / "v1_5_entrypoint_inventory.csv"
    md_path = output_dir / "v1_5_formal_entrypoints.md"
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    _write_csv(csv_path, rows)
    _write_markdown(md_path, rows, summary)

    print(
        json.dumps(
            {
                "entrypoint_count": len(rows),
                "category_summary": summary,
                "json": str(json_path),
                "csv": str(csv_path),
                "markdown": str(md_path),
            },
            ensure_ascii=False,
            indent=2,
        ),
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
