"""Plot helpers for the offline absorbance debugger."""

from .charts import (
    plot_absorbance_compare,
    plot_absorbance_model_fit_by_temp,
    plot_absorbance_model_fit_overall,
    plot_absorbance_model_old_vs_new,
    plot_absorbance_model_residual_hist,
    plot_absorbance_model_residual_vs_target,
    plot_absorbance_model_residual_vs_temp,
    plot_error_boxplot,
    plot_error_hist,
    plot_error_vs_target_ppm,
    plot_error_vs_temp,
    plot_per_temp_compare,
    plot_pressure_compare,
    plot_ratio_series,
    plot_r0_fit,
    plot_temperature_fit,
    plot_timeseries_base_final,
    plot_zero_compare,
    plot_zero_drift,
)

__all__ = [
    "plot_absorbance_compare",
    "plot_absorbance_model_fit_by_temp",
    "plot_absorbance_model_fit_overall",
    "plot_absorbance_model_old_vs_new",
    "plot_absorbance_model_residual_hist",
    "plot_absorbance_model_residual_vs_target",
    "plot_absorbance_model_residual_vs_temp",
    "plot_error_boxplot",
    "plot_error_hist",
    "plot_error_vs_target_ppm",
    "plot_error_vs_temp",
    "plot_per_temp_compare",
    "plot_pressure_compare",
    "plot_ratio_series",
    "plot_r0_fit",
    "plot_temperature_fit",
    "plot_timeseries_base_final",
    "plot_zero_compare",
    "plot_zero_drift",
]
