from __future__ import annotations

from importlib import import_module
from typing import Any


__all__ = [
    "CalibrationPhase",
    "CalibrationPoint",
    "CalibrationService",
    "CalibrationStatus",
    "DataWriter",
    "DeviceFactory",
    "DeviceInfo",
    "DeviceManager",
    "DeviceStatus",
    "DeviceType",
    "Event",
    "EventBus",
    "EventType",
    "CompiledPlan",
    "PlanCompiler",
    "PointFilter",
    "PointParser",
    "RefitFilteringResult",
    "ResultStore",
    "RunLogger",
    "RunSession",
    "SamplingResult",
    "StateManager",
    "StabilityChecker",
    "StabilityResult",
    "StabilityType",
    "TemperatureGroup",
    "WorkflowOrchestrator",
    "Co2RouteStep",
    "FinalizeStep",
    "H2oRouteStep",
    "PrecheckStep",
    "SamplingStep",
    "StartupStep",
    "TemperatureGroupStep",
    "export_refit_filtering_result",
    "resolve_column_mapping",
    "run_refit_filtering",
    # V1.3 P0: Uncertainty GUM engine
    "GUMUncertaintyEngine",
    "UncertaintyInput",
    "CorrelationPair",
    "BudgetResult",
    "DistributionType",
    # V1.3 P0: Method confirmation engine
    "MethodConfirmationEngine",
    "ValidationItem",
    "ValidationResult",
    "VerificationDigest",
    "ValidationCategory",
    "ValidationStatus",
    "build_default_validation_matrix",
    # V1.3 P0: Electronic signature & approval chain
    "ElectronicSignature",
    "ApprovalChain",
    "ApprovalStep",
    "SignatureIntent",
    "ApprovalChainStatus",
    "create_electronic_signature",
    "compute_content_hash",
    "verify_content_hash",
    "create_coefficient_release_chain",
    "create_report_signoff_chain",
    "create_scope_release_chain",
    # V1.3 P0/P1: Conformity, acceptance, governance
    "ConformityStatementProfile",
    "AcceptanceContract",
    "StatementTemplateVersion",
    "ConformityStatementType",
    "GuardBandPolicy",
    "TamperProofStore",
    "IntegritySeal",
    "RetentionPolicy",
    "ArchivalStrategy",
    "ArchiveFormat",
    "DEFAULT_RETENTION_POLICIES",
    "CALIBRATION_CERTIFICATE_TEMPLATE_ZH",
    "CONFORMITY_STATEMENT_TEMPLATE_ZH",
    # V1.3 P3: Scope comparison view
    "ScopeComparisonView",
    "ScopeComparisonResult",
    "ScopeComparisonRow",
]

_EXPORT_MAP = {
    "CalibrationPhase": (".calibration_service", "CalibrationPhase"),
    "CalibrationPoint": (".models", "CalibrationPoint"),
    "CalibrationService": (".calibration_service", "CalibrationService"),
    "CalibrationStatus": (".models", "CalibrationStatus"),
    "DataWriter": (".data_writer", "DataWriter"),
    "DeviceFactory": (".device_factory", "DeviceFactory"),
    "DeviceInfo": (".device_manager", "DeviceInfo"),
    "DeviceManager": (".device_manager", "DeviceManager"),
    "DeviceStatus": (".device_manager", "DeviceStatus"),
    "DeviceType": (".device_factory", "DeviceType"),
    "Event": (".event_bus", "Event"),
    "EventBus": (".event_bus", "EventBus"),
    "EventType": (".event_bus", "EventType"),
    "CompiledPlan": (".plan_compiler", "CompiledPlan"),
    "PlanCompiler": (".plan_compiler", "PlanCompiler"),
    "PointFilter": (".point_parser", "PointFilter"),
    "PointParser": (".point_parser", "PointParser"),
    "RefitFilteringResult": (".refit_filtering", "RefitFilteringResult"),
    "ResultStore": (".result_store", "ResultStore"),
    "RunLogger": (".run_logger", "RunLogger"),
    "RunSession": (".session", "RunSession"),
    "SamplingResult": (".models", "SamplingResult"),
    "StateManager": (".state_manager", "StateManager"),
    "StabilityChecker": (".stability_checker", "StabilityChecker"),
    "StabilityResult": (".stability_checker", "StabilityResult"),
    "StabilityType": (".stability_checker", "StabilityType"),
    "TemperatureGroup": (".point_parser", "TemperatureGroup"),
    "WorkflowOrchestrator": (".orchestrator", "WorkflowOrchestrator"),
    "Co2RouteStep": (".workflow_steps", "Co2RouteStep"),
    "FinalizeStep": (".workflow_steps", "FinalizeStep"),
    "H2oRouteStep": (".workflow_steps", "H2oRouteStep"),
    "PrecheckStep": (".workflow_steps", "PrecheckStep"),
    "SamplingStep": (".workflow_steps", "SamplingStep"),
    "StartupStep": (".workflow_steps", "StartupStep"),
    "TemperatureGroupStep": (".workflow_steps", "TemperatureGroupStep"),
    "export_refit_filtering_result": (".refit_filtering", "export_refit_filtering_result"),
    "resolve_column_mapping": (".refit_filtering", "resolve_column_mapping"),
    "run_refit_filtering": (".refit_filtering", "run_refit_filtering"),
    # V1.3 P0: Uncertainty GUM engine
    "GUMUncertaintyEngine": (".uncertainty_engine", "GUMUncertaintyEngine"),
    "UncertaintyInput": (".uncertainty_engine", "UncertaintyInput"),
    "CorrelationPair": (".uncertainty_engine", "CorrelationPair"),
    "BudgetResult": (".uncertainty_engine", "BudgetResult"),
    "DistributionType": (".uncertainty_engine", "DistributionType"),
    # V1.3 P0: Method confirmation engine
    "MethodConfirmationEngine": (".method_confirmation_engine", "MethodConfirmationEngine"),
    "ValidationItem": (".method_confirmation_engine", "ValidationItem"),
    "ValidationResult": (".method_confirmation_engine", "ValidationResult"),
    "VerificationDigest": (".method_confirmation_engine", "VerificationDigest"),
    "ValidationCategory": (".method_confirmation_engine", "ValidationCategory"),
    "ValidationStatus": (".method_confirmation_engine", "ValidationStatus"),
    "build_default_validation_matrix": (".method_confirmation_engine", "build_default_validation_matrix"),
    # V1.3 P0: Electronic signature & approval chain
    "ElectronicSignature": (".electronic_signature", "ElectronicSignature"),
    "ApprovalChain": (".electronic_signature", "ApprovalChain"),
    "ApprovalStep": (".electronic_signature", "ApprovalStep"),
    "SignatureIntent": (".electronic_signature", "SignatureIntent"),
    "ApprovalChainStatus": (".electronic_signature", "ApprovalChainStatus"),
    "create_electronic_signature": (".electronic_signature", "create_electronic_signature"),
    "compute_content_hash": (".electronic_signature", "compute_content_hash"),
    "verify_content_hash": (".electronic_signature", "verify_content_hash"),
    "create_coefficient_release_chain": (".electronic_signature", "create_coefficient_release_chain"),
    "create_report_signoff_chain": (".electronic_signature", "create_report_signoff_chain"),
    "create_scope_release_chain": (".electronic_signature", "create_scope_release_chain"),
    # V1.3 P0/P1: Conformity, acceptance, governance
    "ConformityStatementProfile": (".conformity_and_governance_objects", "ConformityStatementProfile"),
    "AcceptanceContract": (".conformity_and_governance_objects", "AcceptanceContract"),
    "StatementTemplateVersion": (".conformity_and_governance_objects", "StatementTemplateVersion"),
    "ConformityStatementType": (".conformity_and_governance_objects", "ConformityStatementType"),
    "GuardBandPolicy": (".conformity_and_governance_objects", "GuardBandPolicy"),
    "TamperProofStore": (".conformity_and_governance_objects", "TamperProofStore"),
    "IntegritySeal": (".conformity_and_governance_objects", "IntegritySeal"),
    "RetentionPolicy": (".conformity_and_governance_objects", "RetentionPolicy"),
    "ArchivalStrategy": (".conformity_and_governance_objects", "ArchivalStrategy"),
    "ArchiveFormat": (".conformity_and_governance_objects", "ArchiveFormat"),
    "DEFAULT_RETENTION_POLICIES": (".conformity_and_governance_objects", "DEFAULT_RETENTION_POLICIES"),
    "CALIBRATION_CERTIFICATE_TEMPLATE_ZH": (".conformity_and_governance_objects", "CALIBRATION_CERTIFICATE_TEMPLATE_ZH"),
    "CONFORMITY_STATEMENT_TEMPLATE_ZH": (".conformity_and_governance_objects", "CONFORMITY_STATEMENT_TEMPLATE_ZH"),
    # V1.3 P3: Scope comparison view
    "ScopeComparisonView": (".scope_comparison_view", "ScopeComparisonView"),
    "ScopeComparisonResult": (".scope_comparison_view", "ScopeComparisonResult"),
    "ScopeComparisonRow": (".scope_comparison_view", "ScopeComparisonRow"),
}


def __getattr__(name: str) -> Any:
    target = _EXPORT_MAP.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attr_name = target
    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
